MAFALDA_FALLACY_DEFINITIONS = {
'Abusive Ad Hominem': "This fallacy involves attacking a person's character or motives instead of addressing the substance of their argument.", 
'Tu Quoque': "This fallacy occurs when someone's argument is dismissed because they are accused of acting inconsistently with their claim, rather than addressing the argument itself.", 
'Guilt by Association': 'This fallacy involves discrediting an idea or person based on their association with another person, group, or idea that is viewed negatively.', 
'Ad Populum': 'This fallacy involves claiming that an idea or action is valid because it is popular or widely accepted.', 
'Appeal to Nature': 'This fallacy occurs when something is assumed to be good or desirable simply because it is natural, while its unnatural counterpart is assumed to be bad or undesirable.', 
'Appeal to Tradition': 'This fallacy involves arguing that something should continue to be done a certain way because it has always been done that way, rather than evaluating its merits.', 
'Appeal to Authority': 'This fallacy occurs when an argument relies on the opinion or endorsement of an authority figure who may not have relevant expertise or whose expertise is questionable. When applicable, a scientific consensus is not an appeal to authority.', 
'Causal Oversimplification': 'This fallacy occurs when a complex issue is reduced to a single cause and effect, oversimplifying the actual relationships between events or factors.', 
'Hasty Generalization': 'This fallacy occurs when a conclusion is drawn based on insufficient or unrepresentative evidence.', 
'False Causality': 'This fallacy involves incorrectly assuming that one event causes another, usually based on temporal order or correlation rather than a proven causal relationship.', 
'False Analogy': 'This fallacy involves making an analogy between two elements based on superficial resemblance.', 
'False Dilemma': 'This fallacy occurs when only two options are presented in an argument, even though more options may exist.', 
'Slippery Slope': 'This fallacy occurs when it is claimed that a small step will inevitably lead to a chain of events, resulting in a significant negative outcome.', 
'Fallacy of Division': 'This fallacy involves assuming that if something is true for a whole, it must also be true of all or some of its parts.', 
'Strawman Fallacy': "This fallacy involves misrepresenting an opponent's argument, making it easier to attack and discredit.", 
'Circular Reasoning': 'This fallacy occurs when an argument assumes the very thing it is trying to prove, resulting in a circular and logically invalid argument.', 
'Equivocation': 'This fallacy involves using ambiguous language or changing the meaning of a term within an argument, leading to confusion and false conclusions.', 
'Appeal to Positive Emotion': 'This fallacy occurs when a positive emotion, like hope, optimism, happiness, or pleasure, is used as the main justification for an argument, rather than logical reasoning or evidence.', 
'Appeal to Anger': 'This fallacy involves using anger or indignation as the main justification for an argument, rather than logical reasoning or evidence.', 
'Appeal to Fear': 'This fallacy occurs when fear or threats are used as the main justification for an argument, rather than logical reasoning or evidence.', 
'Appeal to Pity': 'This fallacy involves using sympathy or compassion as the main justification for an argument, rather than logical reasoning or evidence.', 
'Appeal to Ridicule': "This fallacy occurs when an opponent's argument is portrayed as absurd or ridiculous with the intention of discrediting it.", 
'Appeal to Worse Problems': 'This fallacy involves dismissing an issue or problem by claiming that there are more important issues to deal with, instead of addressing the argument at hand. This fallacy is also known as the "relative privation" fallacy.'
}
MAFALDA_FALLACY_LOGICAL_DEFINITIONS = {
'Abusive Ad Hominem': "E claims P. E's character is attacked (A). Therefore, negate P.", 
'Tu Quoque': 'E claims P, but E is acting as if negate P. Therefore negate P.', 
'Guilt by Association': "E1 claims P. Also E2 claims P, and E2's character is attacked (A). Therefore, negate P. OR E1 claims P. E2's character is attacked (A) and is similar to E1 . Therefore negate P.", 
'Ad Populum': 'A lot of people believe/do P. Therefore, P. OR Only a few people believe/do P. Therefore, negate P.', 
'Appeal to Nature': 'P1 is natural. P2 is not natural. Therefore, P1 is better than P2. OR P1 is natural, therefore P1 is good.', 
'Appeal to Tradition': 'We have been doing P for generations. Therefore, we should keep doing P. OR Our ancestors thought P. Therefore, P.', 
'Appeal to Authority': 'E claims P (when E is seen as an authority on the facts relevant to P). Therefore, P.', 
'Causal Oversimplification': 'P1 caused C (although P2, P3, P4, etc. also contributed to C.)', 
'Hasty Generalization': 'Sample E1 is taken from population E. (Sample E1 is a very small part of population E.) Conclusion C is drawn from sample E1.', 
'False Causality': 'P is associated with C (when the link is mostly temporal and not logical). Therefore, P causes C.', 
'False Analogy': 'E1 is like E2. E2 has property P. Therefore, E1 has property P. (but E1 really is not too much like E2)', 
'False Dilemma': 'Either P1 or P2, while there are other possibilities. OR Either P1, P2, or P3, while there are other possibilities.', 
'Slippery Slope': 'P1 implies P2, then P2 implies P3,... then C which is negative. Therefore, negate P1.', 
'Fallacy of Division': 'E1 is part of E, E has property P. Therefore, E1 has property P.', 
'Strawman Fallacy': "E1 claims P. E2 restates E1's claim (in a distorted way P*). E2 attacks (A) P*. Therefore, negate P.", 
'Circular Reasoning': 'C because of P. P because of C. OR C because C.', 
'Equivocation': 'No logical form: P1 uses a term T that has a meaning M1. P2 uses the term T with the meaning M2 to mislead.', 
'Appeal to Positive Emotion': 'P is positive. Therefore, P.', 
'Appeal to Anger': 'E claims P. E is outraged. Therefore, P. Or E1 claims P. E2 is outraged by P. Therefore, P (or negate P depending on the situation).', 
'Appeal to Fear': 'If negate P1, something terrible P2 will happen. Therefore, P1.', 
'Appeal to Pity': 'P which is pitiful therefore C, with only a superficial link between P and C', 
'Appeal to Ridicule': "E1 claims P. E2 makes P look ridiculous, by misrepresenting P (P'). Therefore, negate P.", 
'Appeal to Worse Problems': 'P1 is presented. P2 is presented as a best-case. Therefore, P1 is not that good. OR P 1is presented. P2 is presented as a worst-case. Therefore, P1 is very good.'
}